Repository optimizely/python-sdk, pull requests merged in 2020-07, with the labels that each got.

#288 ci: add source clear as a separate stage
  .travis.yml
Labels: :robot: 4 hrs

#284 Removes spell check of md files stage from travis.yml
  .travis.yml
Labels: :robot: 12 hrs

#283 fix: change datafile accessor feature to return a string representation of datafile
  optimizely/optimizely_config.py
  optimizely/project_config.py
  tests/test_optimizely_config.py
Labels: :robot: 24 hrs

#292 ci: Run source clear before linting and tests.
  .travis.yml
Labels: :robot: 24 hrs
